# Generated by Django 4.2 on 2025-09-17 01:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo')),
                ('nome', models.CharField(help_text='Nome da cidade', max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('slug', models.SlugField(blank=True, help_text='Slug para URLs amigáveis', max_length=120)),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['estado__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Comodidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo')),
                ('nome', models.CharField(help_text='Nome da comodidade (ex: Ar-condicionado, Maca)', max_length=100, unique=True)),
                ('icone', models.CharField(blank=True, help_text="Nome do ícone (ex: 'air-conditioning', 'bed')", max_length=50)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada da comodidade')),
                ('is_destaque', models.BooleanField(default=False, help_text='Comodidade aparece em destaque nos filtros')),
                ('slug', models.SlugField(blank=True, help_text='Slug para URLs amigáveis', max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Comodidade',
                'verbose_name_plural': 'Comodidades',
                'ordering': ['-is_destaque', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo')),
                ('nome', models.CharField(help_text='Nome da especialidade/terapia', max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição da especialidade')),
                ('categoria', models.CharField(blank=True, help_text='Categoria da terapia (ex: Massagem, Energética)', max_length=50)),
                ('slug', models.SlugField(blank=True, help_text='Slug para URLs amigáveis', max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo')),
                ('nome', models.CharField(help_text='Nome completo do estado', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('sigla', models.CharField(help_text='Sigla do estado (ex: RJ, SP)', max_length=2, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Slug para URLs amigáveis', max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Espaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('nome', models.CharField(help_text='Nome do espaço terapêutico', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Slug para URLs amigáveis', max_length=220, unique=True)),
                ('descricao_breve', models.TextField(help_text='Descrição breve para cards (máx 300 caracteres)', max_length=300)),
                ('descricao_completa', models.TextField(blank=True, help_text='Descrição completa do espaço')),
                ('endereco', models.CharField(help_text='Endereço completo do espaço', max_length=255)),
                ('cep', models.CharField(help_text='CEP do espaço', max_length=10, validators=[django.core.validators.RegexValidator(message='CEP deve estar no formato 12345-678', regex='^\\d{5}-?\\d{3}$')])),
                ('bairro', models.CharField(help_text='Bairro do espaço', max_length=100)),
                ('tipo_espaco', models.CharField(choices=[('clinica', 'Clínica'), ('centro_holistico', 'Centro Holístico'), ('estudio', 'Estúdio'), ('spa', 'Spa'), ('consultorio', 'Consultório'), ('espaco_compartilhado', 'Espaço Compartilhado'), ('outros', 'Outros')], default='centro_holistico', help_text='Tipo de espaço terapêutico', max_length=50)),
                ('aceita_locacao', models.BooleanField(default=False, help_text='Aceita locação por outros terapeutas')),
                ('tem_acessibilidade', models.BooleanField(default=False, help_text='Espaço possui acessibilidade')),
                ('disponibilidade', models.JSONField(blank=True, default=list, help_text='Períodos de disponibilidade (lista de períodos)')),
                ('telefone', models.CharField(help_text='Telefone para contato', max_length=20, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (11) 99999-9999', regex='^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$')])),
                ('email', models.EmailField(help_text='Email para contato', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('whatsapp', models.CharField(blank=True, help_text='WhatsApp para contato', max_length=20, validators=[django.core.validators.RegexValidator(message='WhatsApp deve estar no formato (11) 99999-9999', regex='^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$')])),
                ('website', models.URLField(blank=True, help_text='Site oficial do espaço')),
                ('instagram', models.CharField(blank=True, help_text='Usuário do Instagram (sem @)', max_length=50)),
                ('is_verificado', models.BooleanField(default=False, help_text='Espaço foi verificado pela equipe')),
                ('is_premium', models.BooleanField(default=False, help_text='Espaço possui plano premium')),
                ('is_destaque', models.BooleanField(default=False, help_text='Espaço aparece em destaque na home')),
                ('data_verificacao', models.DateTimeField(blank=True, help_text='Data da verificação', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Espaço está ativo na plataforma')),
                ('foto_principal', models.ImageField(blank=True, help_text='Foto principal do espaço', null=True, upload_to='espacos/fotos/')),
                ('foto_galeria', models.JSONField(blank=True, default=list, help_text='Lista de URLs das fotos da galeria')),
                ('cidade', models.ForeignKey(help_text='Cidade onde está localizado', on_delete=django.db.models.deletion.CASCADE, related_name='espacos', to='espacos.cidade')),
                ('comodidades', models.ManyToManyField(blank=True, help_text='Comodidades disponíveis no espaço', related_name='espacos', to='espacos.comodidade')),
                ('especialidades', models.ManyToManyField(blank=True, help_text='Terapias oferecidas no espaço', related_name='espacos', to='espacos.especialidade')),
                ('responsavel', models.ForeignKey(help_text='Usuário responsável pelo espaço', on_delete=django.db.models.deletion.CASCADE, related_name='espacos_gerenciados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Espaço Terapêutico',
                'verbose_name_plural': 'Espaços Terapêuticos',
                'ordering': ['-is_destaque', '-is_premium', '-is_verificado', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ContatoEspaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('nome', models.CharField(help_text='Nome da pessoa que está entrando em contato', max_length=100)),
                ('email', models.EmailField(help_text='Email para resposta', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('telefone', models.CharField(blank=True, help_text='Telefone para contato', max_length=20, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (11) 99999-9999', regex='^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$')])),
                ('assunto', models.CharField(help_text='Assunto da mensagem', max_length=200)),
                ('mensagem', models.TextField(help_text='Mensagem para o espaço')),
                ('is_respondido', models.BooleanField(default=False, help_text='Contato foi respondido')),
                ('espaco', models.ForeignKey(help_text='Espaço contatado', on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='espacos.espaco')),
            ],
            options={
                'verbose_name': 'Contato de Espaço',
                'verbose_name_plural': 'Contatos de Espaços',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(help_text='Estado ao qual a cidade pertence', on_delete=django.db.models.deletion.CASCADE, related_name='cidades_espacos', to='espacos.estado'),
        ),
        migrations.CreateModel(
            name='AvaliacaoEspaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('nota', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Nota de 1 a 5 estrelas')),
                ('comentario', models.TextField(help_text='Comentário sobre o espaço (máx 500 caracteres)', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Avaliação está ativa')),
                ('espaco', models.ForeignKey(help_text='Espaço avaliado', on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='espacos.espaco')),
                ('usuario', models.ForeignKey(help_text='Usuário que fez a avaliação', on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_espacos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliação de Espaço',
                'verbose_name_plural': 'Avaliações de Espaços',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EspacoEspecialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('preco_sessao', models.DecimalField(blank=True, decimal_places=2, help_text='Preço da sessão desta especialidade', max_digits=8, null=True)),
                ('duracao_sessao', models.IntegerField(blank=True, help_text='Duração da sessão em minutos', null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações específicas sobre esta especialidade no espaço')),
                ('is_destaque', models.BooleanField(default=False, help_text='Especialidade em destaque neste espaço')),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidades_detalhadas', to='espacos.espaco')),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacos_detalhados', to='espacos.especialidade')),
            ],
            options={
                'verbose_name': 'Especialidade do Espaço',
                'verbose_name_plural': 'Especialidades dos Espaços',
                'ordering': ['-is_destaque', 'especialidade__nome'],
                'unique_together': {('espaco', 'especialidade')},
            },
        ),
        migrations.AddIndex(
            model_name='espaco',
            index=models.Index(fields=['cidade', 'is_active'], name='espacos_esp_cidade__54b7ab_idx'),
        ),
        migrations.AddIndex(
            model_name='espaco',
            index=models.Index(fields=['tipo_espaco', 'is_active'], name='espacos_esp_tipo_es_64fdd6_idx'),
        ),
        migrations.AddIndex(
            model_name='espaco',
            index=models.Index(fields=['is_destaque', 'is_premium'], name='espacos_esp_is_dest_7d5283_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cidade',
            unique_together={('nome', 'estado')},
        ),
        migrations.AlterUniqueTogether(
            name='avaliacaoespaco',
            unique_together={('espaco', 'usuario')},
        ),
    ]
