# Generated by Django 4.2 on 2025-10-04 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_estado_cidade'),
        ('espacos', '0001_initial_espacos_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espaco',
            name='cidade',
            field=models.ForeignKey(help_text='Cidade onde está localizado', on_delete=django.db.models.deletion.CASCADE, related_name='espacos', to='core.cidade'),
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
