# Generated by Django 5.2.7 on 2025-10-12 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_especialidade'),
        ('espacos', '0002_alter_espaco_cidade_delete_cidade_delete_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacoespecialidade',
            name='especialidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacos_detalhados', to='core.especialidade'),
        ),
        migrations.AlterField(
            model_name='espaco',
            name='especialidades',
            field=models.ManyToManyField(blank=True, help_text='Terapias oferecidas no espaço', related_name='espacos', to='core.especialidade'),
        ),
        migrations.DeleteModel(
            name='Especialidade',
        ),
    ]
