# Generated by Django 5.2.7 on 2025-10-13 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_especialidade'),
        ('espacos', '0003_alter_espacoespecialidade_especialidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='espaco',
            name='cidade_texto',
            field=models.CharField(blank=True, help_text='Nome da cidade para países fora do Brasil', max_length=100, verbose_name='Cidade (outros países)'),
        ),
        migrations.AddField(
            model_name='espaco',
            name='estado',
            field=models.ForeignKey(blank=True, help_text='Estado onde o espaço está (apenas Brasil)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='espacos', to='core.estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='espaco',
            name='pais',
            field=models.ForeignKey(blank=True, help_text='País onde o espaço está localizado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='espacos', to='core.pais', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='espaco',
            name='cidade',
            field=models.ForeignKey(blank=True, help_text='Cidade onde está localizado - apenas para Brasil', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='espacos', to='core.cidade', verbose_name='Cidade (Brasil)'),
        ),
        migrations.AlterField(
            model_name='espaco',
            name='endereco',
            field=models.CharField(blank=True, help_text='Endereço completo do espaço', max_length=255),
        ),
    ]
