# Generated by Django 5.2.7 on 2025-10-13 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacos', '0004_espaco_cidade_texto_espaco_estado_espaco_pais_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoGaleriaEspaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('imagem', models.ImageField(help_text='Foto da galeria do espaço', upload_to='espacos/galeria/', verbose_name='Foto')),
                ('descricao', models.CharField(blank=True, help_text='Descrição opcional da foto', max_length=200, verbose_name='Descrição')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição da foto', verbose_name='Ordem')),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_galeria', to='espacos.espaco', verbose_name='Espaço')),
            ],
            options={
                'verbose_name': 'Foto da Galeria',
                'verbose_name_plural': 'Fotos da Galeria',
                'ordering': ['ordem', 'created_at'],
            },
        ),
    ]
