# Generated by Django 4.2.15 on 2025-10-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("espacos", "0005_fotogaleriaespaco"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comodidade",
            name="descricao",
            field=models.TextField(
                blank=True,
                help_text="Descrição detalhada da comodidade",
                verbose_name="Descrição",
            ),
        ),
        migrations.AlterField(
            model_name="comodidade",
            name="icone",
            field=models.CharField(
                choices=[
                    ("wifi", "📶 Wi-Fi / Internet"),
                    ("parking", "🅿️ Estacionamento"),
                    ("coffee", "☕ Café / Cozinha"),
                    ("wheelchair", "♿ Acessibilidade"),
                    ("air-conditioner", "❄️ Ar Condicionado"),
                    ("music", "🎵 Música Ambiente"),
                    ("book", "📚 Biblioteca"),
                    ("meditation", "🧘 Sala de Meditação"),
                    ("shower", "🚿 Banheiro Privativo"),
                    ("tv", "📺 TV / Projetor"),
                    ("plant", "🌿 Jardim / Área Verde"),
                    ("reception", "👥 Recepção"),
                    ("waiting-room", "🪑 Sala de Espera"),
                    ("tea", "🍵 Chá / Infusões"),
                    ("water", "💧 Água / Bebedouro"),
                    ("printer", "🖨️ Impressora"),
                    ("blanket", "🛋️ Divã / Poltronas"),
                    ("candle", "🕯️ Aromaterapia"),
                    ("soundproof", "🔇 Sala Insonorizada"),
                    ("natural-light", "☀️ Luz Natural"),
                    ("mirror", "🪞 Espelho Grande"),
                    ("storage", "🗄️ Armário / Guarda Volumes"),
                    ("pet-friendly", "🐕 Pet Friendly"),
                    ("children", "👶 Espaço Kids"),
                    ("sink", "🚰 Pia / Lavabo"),
                    ("emergency", "🚨 Kit Primeiros Socorros"),
                    ("security", "🔒 Sistema de Segurança"),
                    ("pharmacy", "💊 Farmácia Próxima"),
                    ("elevator", "🛗 Elevador"),
                    ("ramp", "♿ Rampa de Acesso"),
                ],
                help_text="Selecione o ícone que melhor representa esta comodidade",
                max_length=50,
                verbose_name="Ícone",
            ),
        ),
        migrations.AlterField(
            model_name="comodidade",
            name="is_destaque",
            field=models.BooleanField(
                default=False,
                help_text="Comodidade aparece em destaque nos filtros",
                verbose_name="Destaque",
            ),
        ),
        migrations.AlterField(
            model_name="comodidade",
            name="nome",
            field=models.CharField(
                help_text="Nome da comodidade (ex: Ar-condicionado, Maca)",
                max_length=100,
                unique=True,
                verbose_name="Nome da Comodidade",
            ),
        ),
        migrations.AlterField(
            model_name="comodidade",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Slug para URLs amigáveis (gerado automaticamente)",
                max_length=120,
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
