# Generated by Django 4.2.15 on 2025-10-26 15:38

import django.core.validators
from django.db import migrations, models

def migrar_telefone_para_whatsapp(apps, schema_editor):
    """
    Migra dados do campo telefone para whatsapp se whatsapp estiver vazio
    """
    Espaco = apps.get_model('espacos', 'Espaco')
    
    for espaco in Espaco.objects.all():
        # Se whatsapp estiver vazio e telefone tiver valor, copia telefone para whatsapp
        if hasattr(espaco, 'telefone') and espaco.telefone and not espaco.whatsapp:
            # Remove formatação do telefone antigo
            telefone_limpo = espaco.telefone.replace('(', '').replace(')', '').replace(' ', '').replace('-', '')
            espaco.whatsapp = telefone_limpo
            espaco.save()


class Migration(migrations.Migration):
    dependencies = [
        ("espacos", "0006_alter_comodidade_descricao_alter_comodidade_icone_and_more"),
    ]

    operations = [
        # Migrar dados antes de remover o campo telefone
        migrations.RunPython(
            migrar_telefone_para_whatsapp,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="espaco",
            name="telefone",
        ),
        migrations.AddField(
            model_name="espaco",
            name="facebook",
            field=models.URLField(
                blank=True,
                help_text="URL completa da página no Facebook",
                verbose_name="Facebook",
            ),
        ),
        migrations.AddField(
            model_name="espaco",
            name="tiktok",
            field=models.CharField(
                blank=True,
                help_text="Usuário do TikTok sem @ (ex: espacovital)",
                max_length=100,
                verbose_name="TikTok",
            ),
        ),
        migrations.AddField(
            model_name="espaco",
            name="whatsapp_ativo",
            field=models.BooleanField(
                default=False,
                help_text="Marque se este número possui WhatsApp ativo",
                verbose_name="Este número é WhatsApp?",
            ),
        ),
        migrations.AddField(
            model_name="espaco",
            name="youtube",
            field=models.URLField(
                blank=True,
                help_text="URL completa do canal no YouTube",
                verbose_name="YouTube",
            ),
        ),
        migrations.AlterField(
            model_name="espaco",
            name="email",
            field=models.EmailField(
                help_text="E-mail para contato do espaço",
                max_length=254,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="E-mail",
            ),
        ),
        migrations.AlterField(
            model_name="espaco",
            name="instagram",
            field=models.CharField(
                blank=True,
                help_text="Usuário do Instagram sem @ (ex: espacovital)",
                max_length=100,
                verbose_name="Instagram",
            ),
        ),
        migrations.AlterField(
            model_name="espaco",
            name="website",
            field=models.URLField(
                blank=True,
                help_text="URL completa do site oficial do espaço",
                verbose_name="Site",
            ),
        ),
        migrations.AlterField(
            model_name="espaco",
            name="whatsapp",
            field=models.CharField(
                blank=True,
                help_text="Telefone com DDD (somente números). Ex: 21987654321",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Digite apenas números (DDD + telefone). Ex: 21987654321",
                        regex="^\\d{10,11}$",
                    )
                ],
                verbose_name="Telefone/WhatsApp",
            ),
        ),
    ]
