# Generated by Django 4.2.15 on 2025-10-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("espacos", "0007_add_redes_sociais"),
    ]

    operations = [
        migrations.AddField(
            model_name="espaco",
            name="horarios_funcionamento",
            field=models.TextField(
                blank=True,
                help_text="Descreva os horários de funcionamento do espaço. Ex: Segunda a Sexta: 08h às 18h | Sábado: 09h às 14h",
                max_length=500,
                verbose_name="Horários de Funcionamento",
            ),
        ),
    ]
