# Generated by Django 4.2.15 on 2025-10-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("espacos", "0007_add_redes_sociais"),
    ]

    operations = [
    migrations.AddField(
        model_name='espaco',
        name='horarios_semana',
        field=models.JSONField(
            blank=True,
            default=dict,
            help_text='Horários de funcionamento organizados por dia da semana...',
            verbose_name='Horários da Semana'
        ),
    ),
    ]
