# Generated by Django 4.2.15 on 2025-10-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("espacos", "0008_add_horarios_funcionamento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="espaco",
            name="horarios_funcionamento",
        ),
        migrations.AddField(
            model_name="espaco",
            name="horario_fds_abertura",
            field=models.TimeField(
                blank=True,
                help_text="Horário de abertura nos finais de semana",
                null=True,
                verbose_name="Finais de Semana - Abertura",
            ),
        ),
        migrations.AddField(
            model_name="espaco",
            name="horario_fds_fechamento",
            field=models.TimeField(
                blank=True,
                help_text="Horário de fechamento nos finais de semana",
                null=True,
                verbose_name="Finais de Semana - Fechamento",
            ),
        ),
        migrations.AddField(
            model_name="espaco",
            name="horario_manha_abertura",
            field=models.TimeField(
                blank=True,
                help_text="Horário de abertura no período da manhã",
                null=True,
                verbose_name="Manhã - Abertura",
            ),
        ),
        migrations.AddField(
            model_name="espaco",
            name="horario_manha_fechamento",
            field=models.TimeField(
                blank=True,
                help_text="Horário de fechamento no período da manhã",
                null=True,
                verbose_name="Manhã - Fechamento",
            ),
        ),
        migrations.AddField(
            model_name="espaco",
            name="horario_noite_abertura",
            field=models.TimeField(
                blank=True,
                help_text="Horário de abertura no período da noite",
                null=True,
                verbose_name="Noite - Abertura",
            ),
        ),
        migrations.AddField(
            model_name="espaco",
            name="horario_noite_fechamento",
            field=models.TimeField(
                blank=True,
                help_text="Horário de fechamento no período da noite",
                null=True,
                verbose_name="Noite - Fechamento",
            ),
        ),
        migrations.AddField(
            model_name="espaco",
            name="horario_tarde_abertura",
            field=models.TimeField(
                blank=True,
                help_text="Horário de abertura no período da tarde",
                null=True,
                verbose_name="Tarde - Abertura",
            ),
        ),
        migrations.AddField(
            model_name="espaco",
            name="horario_tarde_fechamento",
            field=models.TimeField(
                blank=True,
                help_text="Horário de fechamento no período da tarde",
                null=True,
                verbose_name="Tarde - Fechamento",
            ),
        ),
    ]
