# Generated by Django 4.2.15 on 2025-11-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("espacos", "0008_remove_espaco_disponibilidade_espaco_horarios_semana"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="espaco",
            name="disponibilidade",
        ),
        migrations.AlterField(
            model_name="espaco",
            name="horarios_semana",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Horários de funcionamento organizados por dia da semana.",
                verbose_name="Horários da Semana",
            ),
        ),
    ]
