# Generated by Django 4.2 on 2025-09-28 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terapeutas', '0002_multiplas_cidades'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='terapeuta',
            name='terapeutas__cidade__8466f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='terapeuta',
            name='terapeutas_cidade_principal_idx',
        ),
        migrations.RemoveField(
            model_name='terapeuta',
            name='cidade',
        ),
    ]
