# Generated by Django 4.2 on 2025-10-03 02:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terapeutas', '0004_para_quem_multiplo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terapeuta',
            name='bio_completa',
            field=ckeditor.fields.RichTextField(help_text='Descrição detalhada do perfil profissional', verbose_name='Bio Completa'),
        ),
    ]
