# Generated by Django 4.2 on 2025-10-04 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_estado_cidade'),
        ('terapeutas', '0005_alter_terapeuta_bio_completa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terapeuta',
            name='cidade_principal',
            field=models.ForeignKey(help_text='Cidade principal onde atua', on_delete=django.db.models.deletion.PROTECT, related_name='terapeutas_principal', to='core.cidade', verbose_name='Cidade Principal'),
        ),
        migrations.AlterField(
            model_name='terapeuta',
            name='cidades_atendimento',
            field=models.ManyToManyField(blank=True, help_text='Outras cidades onde também atende (além da principal)', related_name='terapeutas_adicionais', to='core.cidade', verbose_name='Outras Cidades de Atendimento'),
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
