# Generated by Django 4.2 on 2025-10-05 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pais_alter_estado_options_alter_cidade_estado_and_more'),
        ('terapeutas', '0006_alter_terapeuta_cidade_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terapeuta',
            name='pais',
            field=models.ForeignKey(blank=True, help_text='País onde atua', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terapeutas', to='core.pais', verbose_name='País'),
        ),
    ]
