# Generated by Django 4.2 on 2025-10-05 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cidade_unique_together_cidade_pais_and_more'),
        ('terapeutas', '0007_terapeuta_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='terapeuta',
            name='cidade_texto',
            field=models.CharField(blank=True, help_text='Nome da cidade para países fora do Brasil', max_length=100, verbose_name='Cidade (outros países)'),
        ),
        migrations.AlterField(
            model_name='terapeuta',
            name='cidade_principal',
            field=models.ForeignKey(blank=True, help_text='Cidade principal onde atua - apenas para Brasil', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terapeutas_principal', to='core.cidade', verbose_name='Cidade Principal (Brasil)'),
        ),
    ]
