# Generated by Django 4.2 on 2025-10-05 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cidade_unique_together_cidade_pais_and_more'),
        ('terapeutas', '0008_terapeuta_cidade_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terapeuta',
            name='estado',
            field=models.ForeignKey(blank=True, help_text='Estado onde atua (apenas Brasil)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terapeutas', to='core.estado', verbose_name='Estado'),
        ),
    ]
