# Generated by Django 5.2.7 on 2025-10-12 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_especialidade'),
        ('terapeutas', '0009_terapeuta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terapeutaespecialidade',
            name='especialidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.especialidade', verbose_name='Especialidade'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='especialidade_interesse',
            field=models.ForeignKey(blank=True, help_text='Especialidade que despertou interesse', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.especialidade', verbose_name='Especialidade de Interesse'),
        ),
        migrations.AlterField(
            model_name='terapeuta',
            name='especialidades',
            field=models.ManyToManyField(help_text='Especialidades que o terapeuta oferece', through='terapeutas.TerapeutaEspecialidade', to='core.especialidade', verbose_name='Especialidades'),
        ),
        migrations.DeleteModel(
            name='Especialidade',
        ),
    ]
