# Generated by Django 5.2.7 on 2025-10-12 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terapeutas', '0010_alter_terapeutaespecialidade_especialidade_and_more'),
        ('terapeutas', '0010_migrate_especialidades_to_core'),
    ]

    operations = [
    ]
