# Generated by Django 4.2.15 on 2025-10-26 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terapeutas", "0011_merge_20251012_1850"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="terapeuta",
            name="telefone",
        ),
        migrations.AddField(
            model_name="terapeuta",
            name="facebook",
            field=models.URLField(
                blank=True,
                help_text="URL completa do perfil no Facebook",
                verbose_name="Facebook",
            ),
        ),
        migrations.AddField(
            model_name="terapeuta",
            name="instagram",
            field=models.CharField(
                blank=True,
                help_text="Usuário do Instagram sem @ (ex: espacovital)",
                max_length=100,
                verbose_name="Instagram",
            ),
        ),
        migrations.AddField(
            model_name="terapeuta",
            name="tiktok",
            field=models.CharField(
                blank=True,
                help_text="Usuário do TikTok sem @ (ex: espacovital)",
                max_length=100,
                verbose_name="TikTok",
            ),
        ),
        migrations.AddField(
            model_name="terapeuta",
            name="whatsapp_ativo",
            field=models.BooleanField(
                default=False,
                help_text="Marque se este número possui WhatsApp ativo",
                verbose_name="Este número é WhatsApp?",
            ),
        ),
        migrations.AddField(
            model_name="terapeuta",
            name="youtube",
            field=models.URLField(
                blank=True,
                help_text="URL completa do canal no YouTube",
                verbose_name="YouTube",
            ),
        ),
        migrations.AlterField(
            model_name="terapeuta",
            name="whatsapp",
            field=models.CharField(
                blank=True,
                help_text="Telefone com DDD (somente números). Ex: 21987654321",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Digite apenas números (DDD + telefone). Ex: 21987654321",
                        regex="^\\d{10,11}$",
                    )
                ],
                verbose_name="Telefone/WhatsApp",
            ),
        ),
    ]
