# Generated by Django 4.2.15 on 2025-10-26 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("terapeutas", "0012_add_redes_sociais"),
    ]

    operations = [
        migrations.CreateModel(
            name="FotoGaleriaTerapeuta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro",
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização",
                        verbose_name="Atualizado em",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        help_text="Foto da galeria do terapeuta",
                        upload_to="terapeutas/galeria/",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True,
                        help_text="Descrição opcional da foto",
                        max_length=200,
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordem de exibição da foto",
                        verbose_name="Ordem",
                    ),
                ),
                (
                    "terapeuta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos_galeria",
                        to="terapeutas.terapeuta",
                        verbose_name="Terapeuta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto da Galeria",
                "verbose_name_plural": "Fotos da Galeria",
                "ordering": ["ordem", "created_at"],
            },
        ),
    ]
