# Generated by Django 4.2.15 on 2025-11-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terapeutas", "0013_fotogaleriaterapeuta"),
    ]

    operations = [
        migrations.AddField(
            model_name="terapeuta",
            name="data_assinatura_plano",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Quando assinou o plano atual",
                null=True,
                verbose_name="Data de Assinatura do Plano",
            ),
        ),
        migrations.AddField(
            model_name="terapeuta",
            name="plano",
            field=models.CharField(
                choices=[
                    ("basic", "🌱 Basic"),
                    ("premium_a", "⭐ Premium A"),
                    ("premium_s", "💎 Premium S (Categoria S)"),
                ],
                default="basic",
                help_text="Plano atual do terapeuta",
                max_length=20,
                verbose_name="Plano de Assinatura",
            ),
        ),
        migrations.AlterField(
            model_name="terapeuta",
            name="destaque",
            field=models.BooleanField(
                default=False,
                help_text="[DEPRECATED] Use campo plano",
                verbose_name="Em Destaque",
            ),
        ),
        migrations.AlterField(
            model_name="terapeuta",
            name="premium",
            field=models.BooleanField(
                default=False,
                help_text="[DEPRECATED] Use campo plano",
                verbose_name="Premium",
            ),
        ),
    ]
