# Generated by Django 4.2.15 on 2025-12-15 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("terapeutas", "0014_terapeuta_data_assinatura_plano_terapeuta_plano_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="terapeuta",
            name="cpf_cnpj",
            field=models.CharField(
                blank=True,
                help_text="CPF (000.000.000-00) ou CNPJ (00.000.000/0000-00)",
                max_length=18,
                verbose_name="CPF/CNPJ",
            ),
        ),
        migrations.AlterField(
            model_name="terapeuta",
            name="nome_completo",
            field=models.CharField(
                help_text="Nome completo do terapeuta",
                max_length=200,
                verbose_name="Nome Completo",
            ),
        ),
        migrations.AlterField(
            model_name="terapeuta",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="terapeuta",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
    ]
