# Generated by Django 4.2.15 on 2025-12-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "terapeutas",
            "0015_terapeuta_cpf_cnpj_alter_terapeuta_nome_completo_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotogaleriaterapeuta",
            name="ordem",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Ordem de exibição da foto (0 = primeira)",
                verbose_name="Ordem",
            ),
        ),
    ]
