# Generated by Django 4.2 on 2025-10-05 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_estado_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do País')),
                ('codigo', models.CharField(help_text='Código ISO do país (ex: BRA, USA, PRT)', max_length=3, unique=True, verbose_name='Código ISO')),
                ('ddi', models.CharField(blank=True, help_text='Código de discagem internacional (ex: +55, +1, +351)', max_length=5, verbose_name='DDI')),
                ('ativo', models.BooleanField(default=True, help_text='País ativo no sistema', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'ordering': ['nome'], 'verbose_name': 'Estado', 'verbose_name_plural': 'Estados/Províncias'},
        ),
        migrations.AlterField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidades', to='core.estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Estado'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='sigla',
            field=models.CharField(help_text='Sigla do estado (ex: RJ, SP, CA, NY)', max_length=10, verbose_name='Sigla/Código'),
        ),
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='core.pais', verbose_name='País'),
        ),
    ]
