# Generated by Django 4.2 on 2025-10-05 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pais_alter_estado_options_alter_cidade_estado_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cidade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cidade',
            name='pais',
            field=models.ForeignKey(blank=True, help_text='Para países sem estados, vincule a cidade direto ao país', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cidades_diretas', to='core.pais', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cidades', to='core.estado', verbose_name='Estado'),
        ),
    ]
