# Generated by Django 5.2.7 on 2025-10-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cidade_unique_together_cidade_pais_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('nome', models.CharField(help_text='Nome da especialidade/terapia', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Slug para URLs amigáveis', max_length=120, unique=True)),
                ('descricao_curta', models.CharField(blank=True, help_text='Descrição resumida da especialidade', max_length=200)),
                ('descricao_completa', models.TextField(blank=True, help_text='Descrição detalhada da especialidade')),
                ('categoria', models.CharField(blank=True, help_text='Categoria da terapia (ex: Massagem, Energética)', max_length=50)),
                ('cor_destaque', models.CharField(blank=True, default='#6C63FF', help_text='Cor em hexadecimal para destaque (#RRGGBB)', max_length=7)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição (menor aparece primeiro)')),
                ('destaque', models.BooleanField(default=False, help_text='Especialidade aparece em destaque')),
                ('is_active', models.BooleanField(default=True, help_text='Especialidade está ativa no sistema')),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['-destaque', 'ordem', 'nome'],
                'indexes': [models.Index(fields=['destaque', 'is_active'], name='core_especi_destaqu_b5d06c_idx'), models.Index(fields=['ordem'], name='core_especi_ordem_cabaa8_idx')],
            },
        ),
    ]
