# Generated by Django 4.2.15 on 2025-10-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_especialidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="especialidade",
            name="descricao_curta",
            field=models.CharField(
                blank=True,
                help_text="Descrição resumida da especialidade",
                max_length=700,
            ),
        ),
    ]
