# Generated by Django 4.2.15 on 2025-10-26 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_aumentar_descricao_curta_especialidade"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="estado",
            options={
                "ordering": ["nome"],
                "verbose_name": "Estado",
                "verbose_name_plural": "Estados",
            },
        ),
    ]
