# Generated by Django 4.2.15 on 2025-11-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_estado_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="especialidade",
            options={
                "ordering": ["-destaque", "ordem", "nome"],
                "verbose_name": "Especialidade / Terapia",
                "verbose_name_plural": "Especialidades / Terapias",
            },
        ),
        migrations.AddField(
            model_name="especialidade",
            name="beneficios",
            field=models.TextField(
                blank=True,
                help_text="Lista de benefícios da terapia (use marcadores • para listar)",
            ),
        ),
        migrations.AddField(
            model_name="especialidade",
            name="foto",
            field=models.ImageField(
                blank=True,
                help_text="Imagem representativa da terapia (ideal: 800x600px)",
                null=True,
                upload_to="terapias/",
            ),
        ),
        migrations.AlterField(
            model_name="especialidade",
            name="descricao_completa",
            field=models.TextField(
                blank=True,
                help_text="Descrição detalhada da especialidade (para página individual)",
            ),
        ),
        migrations.AlterField(
            model_name="especialidade",
            name="descricao_curta",
            field=models.CharField(
                blank=True,
                help_text="Descrição resumida da especialidade (para cards)",
                max_length=700,
            ),
        ),
        migrations.AlterField(
            model_name="especialidade",
            name="destaque",
            field=models.BooleanField(
                default=False,
                help_text="Aparece nas 10 terapias em destaque na página de Terapias",
            ),
        ),
    ]
