# Generated by Django 4.2.15 on 2025-11-02 19:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_especialidade_options_especialidade_beneficios_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="especialidade",
            name="conteudo_completo",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="\n        Conteúdo detalhado da terapia com seções estruturadas:\n        - Introdução\n        - O que é a terapia\n        - Em que a terapia pode ajudar\n        - O que esperar numa sessão\n        - O que sentirá após uma sessão\n        - Quantas sessões são necessárias\n        - Como escolher um terapeuta\n        ",
                null=True,
                verbose_name="Conteúdo Completo (Editor Rico)",
            ),
        ),
        migrations.AddField(
            model_name="especialidade",
            name="sites_referencia",
            field=models.TextField(
                blank=True,
                help_text="URLs de sites de referência sobre a terapia (uma por linha)",
                null=True,
                verbose_name="Sites de Referência",
            ),
        ),
    ]
