# Generated by Django 4.2.15 on 2025-11-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_especialidade_conteudo_completo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SugestaoTerapia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro",
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização",
                        verbose_name="Atualizado em",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o registro está ativo no sistema",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome completo do usuário",
                        max_length=200,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="E-mail para contato",
                        max_length=254,
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "nome_terapia",
                    models.CharField(
                        help_text="Nome da terapia sugerida",
                        max_length=200,
                        verbose_name="Nome da Terapia",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        help_text="Breve descrição sobre a terapia",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "lida",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se a sugestão foi lida pela equipe",
                        verbose_name="Lida",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sugestão de Terapia",
                "verbose_name_plural": "Sugestões de Terapias",
                "ordering": ["-created_at"],
            },
        ),
    ]
