# Generated by Django 4.2.15 on 2025-12-13 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0011_sugestaoterapia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assinatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro",
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização",
                        verbose_name="Atualizado em",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o registro está ativo no sistema",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Período de Teste"),
                            ("active", "Ativa"),
                            ("suspended", "Suspensa"),
                            ("cancelled", "Cancelada"),
                            ("expired", "Expirada"),
                        ],
                        default="trial",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateField(
                        help_text="Data de início da assinatura",
                        verbose_name="Data de Início",
                    ),
                ),
                (
                    "data_fim_trial",
                    models.DateField(
                        blank=True,
                        help_text="Data de término do período de teste",
                        null=True,
                        verbose_name="Data Fim do Trial",
                    ),
                ),
                (
                    "data_proxima_cobranca",
                    models.DateField(
                        blank=True,
                        help_text="Data da próxima cobrança",
                        null=True,
                        verbose_name="Data Próxima Cobrança",
                    ),
                ),
                (
                    "data_cancelamento",
                    models.DateField(
                        blank=True,
                        help_text="Data em que a assinatura foi cancelada",
                        null=True,
                        verbose_name="Data de Cancelamento",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True,
                        help_text="Observações sobre a assinatura",
                        verbose_name="Observações",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assinatura",
                "verbose_name_plural": "Assinaturas",
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Plano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro",
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização",
                        verbose_name="Atualizado em",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o registro está ativo no sistema",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        choices=[
                            ("gratuito_filiado", "Gratuito Filiado a Espaço"),
                            ("basic", "Basic"),
                            ("premium_a", "Premium A (Terapeuta)"),
                            ("premium_s", "Premium S (Espaço)"),
                            ("premium_s_plus", "Premium S+ (Espaço com Gerenciamento)"),
                            ("combo_a_s", "Combo Premium A + S"),
                            ("combo_a_s_plus", "Combo Premium A + S+"),
                        ],
                        max_length=100,
                        unique=True,
                        verbose_name="Nome do Plano",
                    ),
                ),
                (
                    "nome_exibicao",
                    models.CharField(
                        help_text="Nome que aparece na interface",
                        max_length=100,
                        verbose_name="Nome para Exibição",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        help_text="Descrição resumida do plano",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor mensal em R$",
                        max_digits=10,
                        verbose_name="Valor Mensal",
                    ),
                ),
                (
                    "dias_trial",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Quantidade de dias gratuitos de teste",
                        verbose_name="Dias de Trial",
                    ),
                ),
                (
                    "destaque_busca",
                    models.BooleanField(
                        default=False,
                        help_text="Perfil aparece em destaque nas buscas",
                        verbose_name="Destaque nas Buscas",
                    ),
                ),
                (
                    "badge_verificado",
                    models.BooleanField(
                        default=False,
                        help_text="Exibe badge de verificado no perfil",
                        verbose_name="Badge Verificado",
                    ),
                ),
                (
                    "estatisticas_avancadas",
                    models.BooleanField(
                        default=False,
                        help_text="Acesso a estatísticas avançadas",
                        verbose_name="Estatísticas Avançadas",
                    ),
                ),
                (
                    "suporte_prioritario",
                    models.BooleanField(
                        default=False,
                        help_text="Atendimento prioritário",
                        verbose_name="Suporte Prioritário",
                    ),
                ),
                (
                    "limite_fotos",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Quantidade máxima de fotos no perfil",
                        verbose_name="Limite de Fotos",
                    ),
                ),
                (
                    "vinculos_espacos",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Quantidade de espaços que pode se vincular",
                        verbose_name="Vínculos com Espaços",
                    ),
                ),
                (
                    "gerenciamento_salas",
                    models.BooleanField(
                        default=False,
                        help_text="Permite gerenciar salas (para espaços)",
                        verbose_name="Gerenciamento de Salas",
                    ),
                ),
                (
                    "divulgacao_perfil",
                    models.BooleanField(
                        default=True,
                        help_text="Perfil aparece publicamente no site",
                        verbose_name="Divulgação de Perfil",
                    ),
                ),
                (
                    "max_usuarios",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Limite de usuários neste plano (null = ilimitado)",
                        null=True,
                        verbose_name="Máximo de Usuários",
                    ),
                ),
                (
                    "ordem_exibicao",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordem de exibição na página de planos",
                        verbose_name="Ordem de Exibição",
                    ),
                ),
                (
                    "recomendado",
                    models.BooleanField(
                        default=False,
                        help_text="Destacar como plano recomendado",
                        verbose_name="Plano Recomendado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plano de Assinatura",
                "verbose_name_plural": "Planos de Assinatura",
                "ordering": ["ordem_exibicao", "valor"],
            },
        ),
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro",
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização",
                        verbose_name="Atualizado em",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o registro está ativo no sistema",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código único do voucher (ex: BEMVINDO2024)",
                        max_length=50,
                        unique=True,
                        verbose_name="Código do Voucher",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        help_text="Descrição interna do voucher",
                        max_length=200,
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "tipo_desconto",
                    models.CharField(
                        choices=[
                            ("percentual", "Percentual"),
                            ("valor_fixo", "Valor Fixo"),
                            ("gratuidade", "Período de Gratuidade"),
                        ],
                        default="percentual",
                        max_length=20,
                        verbose_name="Tipo de Desconto",
                    ),
                ),
                (
                    "valor_desconto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Valor em R$ (se fixo) ou % (se percentual)",
                        max_digits=10,
                        null=True,
                        verbose_name="Valor do Desconto",
                    ),
                ),
                (
                    "dias_gratuidade",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Quantidade de dias grátis (15 a 90)",
                        verbose_name="Dias de Gratuidade",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateField(
                        help_text="Data a partir da qual o voucher é válido",
                        verbose_name="Data de Início",
                    ),
                ),
                (
                    "data_expiracao",
                    models.DateField(
                        help_text="Data até quando o voucher é válido",
                        verbose_name="Data de Expiração",
                    ),
                ),
                (
                    "limite_usos",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Quantidade máxima de usos (null = ilimitado)",
                        null=True,
                        verbose_name="Limite de Usos",
                    ),
                ),
                (
                    "usos_realizados",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Usos Realizados"
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vouchers_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "planos_aplicaveis",
                    models.ManyToManyField(
                        help_text="Planos em que o voucher pode ser usado",
                        related_name="vouchers",
                        to="core.plano",
                        verbose_name="Planos Aplicáveis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voucher",
                "verbose_name_plural": "Vouchers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricoAssinatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro",
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização",
                        verbose_name="Atualizado em",
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        help_text="Descrição da ação realizada",
                        max_length=100,
                        verbose_name="Ação",
                    ),
                ),
                (
                    "detalhes",
                    models.TextField(
                        blank=True,
                        help_text="Detalhes adicionais da ação",
                        verbose_name="Detalhes",
                    ),
                ),
                (
                    "assinatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="core.assinatura",
                        verbose_name="Assinatura",
                    ),
                ),
                (
                    "plano_anterior",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historico_anterior",
                        to="core.plano",
                        verbose_name="Plano Anterior",
                    ),
                ),
                (
                    "plano_novo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historico_novo",
                        to="core.plano",
                        verbose_name="Plano Novo",
                    ),
                ),
                (
                    "realizado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acoes_assinatura",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Realizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Assinatura",
                "verbose_name_plural": "Históricos de Assinaturas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="assinatura",
            name="plano",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assinaturas",
                to="core.plano",
                verbose_name="Plano",
            ),
        ),
        migrations.AddField(
            model_name="assinatura",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assinaturas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AddField(
            model_name="assinatura",
            name="voucher_utilizado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assinaturas",
                to="core.voucher",
                verbose_name="Voucher Utilizado",
            ),
        ),
    ]
