# Generated by Django 4.2.15 on 2025-12-29 23:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("terapeutas", "0016_alter_fotogaleriaterapeuta_ordem"),
        ("espacos", "0009_remove_espaco_disponibilidade_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data do Agendamento")),
                ("hora_inicio", models.TimeField(verbose_name="Hora de Início")),
                ("hora_fim", models.TimeField(verbose_name="Hora de Término")),
                (
                    "valor_cobrado",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor cobrado por este agendamento",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Valor Cobrado",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("CONFIRMADO", "Confirmado"),
                            ("CANCELADO", "Cancelado"),
                            ("CONCLUIDO", "Concluído"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "pago",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o pagamento foi confirmado",
                        verbose_name="Pago",
                    ),
                ),
                (
                    "data_pagamento",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora em que o pagamento foi confirmado",
                        null=True,
                        verbose_name="Data do Pagamento",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True,
                        help_text="Observações sobre o agendamento (cliente, tipo de atendimento, etc.)",
                        verbose_name="Observações",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "espaco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agendamentos",
                        to="espacos.espaco",
                        verbose_name="Espaço",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agendamento",
                "verbose_name_plural": "Agendamentos",
                "ordering": ["-data", "-hora_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Sala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Ex: Sala Mandala, Sala Kali, Salão Principal",
                        max_length=100,
                        verbose_name="Nome da Sala",
                    ),
                ),
                (
                    "capacidade",
                    models.PositiveIntegerField(
                        help_text="Número máximo de pessoas", verbose_name="Capacidade"
                    ),
                ),
                (
                    "valor_sessao",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor em R$ para uma sessão",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Valor por Sessão",
                    ),
                ),
                (
                    "duracao_sessao",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Duração padrão em minutos (ex: 60 para 1 hora)",
                        verbose_name="Duração da Sessão (minutos)",
                    ),
                ),
                (
                    "horario_abertura",
                    models.TimeField(
                        help_text="Horário em que a sala abre (ex: 08:00)",
                        verbose_name="Horário de Abertura",
                    ),
                ),
                (
                    "horario_fechamento",
                    models.TimeField(
                        help_text="Horário em que a sala fecha (ex: 20:00)",
                        verbose_name="Horário de Fechamento",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="salas/",
                        verbose_name="Foto da Sala",
                    ),
                ),
                (
                    "comodidades",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Comodidades disponíveis na sala (ar-condicionado, maca, etc.)",
                        verbose_name="Comodidades",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarque para desativar a sala temporariamente",
                        verbose_name="Sala Ativa",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "espaco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salas",
                        to="espacos.espaco",
                        verbose_name="Espaço",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sala",
                "verbose_name_plural": "Salas",
                "ordering": ["espaco", "nome"],
                "unique_together": {("espaco", "nome")},
            },
        ),
        migrations.CreateModel(
            name="PIXConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_chave",
                    models.CharField(
                        choices=[
                            ("CPF", "CPF"),
                            ("CNPJ", "CNPJ"),
                            ("EMAIL", "E-mail"),
                            ("TELEFONE", "Telefone"),
                            ("ALEATORIA", "Chave Aleatória"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Chave PIX",
                    ),
                ),
                (
                    "chave_pix",
                    models.CharField(
                        help_text="Chave PIX para recebimento dos pagamentos",
                        max_length=255,
                        verbose_name="Chave PIX",
                    ),
                ),
                (
                    "nome_recebedor",
                    models.CharField(
                        help_text="Nome que aparecerá no PIX",
                        max_length=255,
                        verbose_name="Nome do Recebedor",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se esta configuração está ativa",
                        verbose_name="Configuração Ativa",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "espaco",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pix_config",
                        to="espacos.espaco",
                        verbose_name="Espaço",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração PIX",
                "verbose_name_plural": "Configurações PIX",
            },
        ),
        migrations.CreateModel(
            name="Multa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        help_text="Ex: Sala deixada suja, Atraso no pagamento, Cancelamento tardio",
                        max_length=255,
                        verbose_name="Motivo da Multa",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Valor da Multa",
                    ),
                ),
                (
                    "data_aplicacao",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora em que a multa foi aplicada",
                        verbose_name="Data de Aplicação",
                    ),
                ),
                (
                    "pago",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se a multa foi paga",
                        verbose_name="Pago",
                    ),
                ),
                (
                    "data_pagamento",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora em que a multa foi paga",
                        null=True,
                        verbose_name="Data do Pagamento",
                    ),
                ),
                (
                    "foto_evidencia",
                    models.ImageField(
                        blank=True,
                        help_text="Foto que comprova o motivo da multa",
                        null=True,
                        upload_to="multas/",
                        verbose_name="Foto de Evidência",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "agendamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multas",
                        to="agendamentos.agendamento",
                        verbose_name="Agendamento Relacionado",
                    ),
                ),
                (
                    "espaco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multas_aplicadas",
                        to="espacos.espaco",
                        verbose_name="Espaço",
                    ),
                ),
                (
                    "terapeuta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multas",
                        to="terapeutas.terapeuta",
                        verbose_name="Terapeuta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Multa",
                "verbose_name_plural": "Multas",
                "ordering": ["-data_aplicacao"],
            },
        ),
        migrations.AddField(
            model_name="agendamento",
            name="sala",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agendamentos",
                to="agendamentos.sala",
                verbose_name="Sala",
            ),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="terapeuta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agendamentos",
                to="terapeutas.terapeuta",
                verbose_name="Terapeuta",
            ),
        ),
        migrations.AddIndex(
            model_name="agendamento",
            index=models.Index(
                fields=["data", "sala"], name="agendamento_data_79db90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agendamento",
            index=models.Index(
                fields=["terapeuta", "status"], name="agendamento_terapeu_ee0754_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agendamento",
            index=models.Index(
                fields=["espaco", "data"], name="agendamento_espaco__e768f3_idx"
            ),
        ),
    ]
