# Generated by Django 4.2.15 on 2025-12-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("espacos", "0009_remove_espaco_disponibilidade_and_more"),
        ("agendamentos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sala",
            name="comodidades",
        ),
        migrations.AddField(
            model_name="sala",
            name="comodidades",
            field=models.ManyToManyField(
                blank=True,
                help_text="Comodidades disponíveis na sala",
                to="espacos.comodidade",
                verbose_name="Comodidades",
            ),
        ),
    ]
