# Generated by Django 4.2.15 on 2026-01-03 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("terapeutas", "0016_alter_fotogaleriaterapeuta_ordem"),
        ("core", "0012_assinatura_plano_voucher_historicoassinatura_and_more"),
        ("espacos", "0009_remove_espaco_disponibilidade_and_more"),
        ("agendamentos", "0002_remove_sala_comodidades_sala_comodidades"),
    ]

    operations = [
        migrations.CreateModel(
            name="VinculoTerapeutaEspaco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Criado Manualmente"),
                            ("CONVITE", "Convite do Espaço"),
                            ("SOLICITACAO", "Solicitação do Terapeuta"),
                            ("VOUCHER", "Voucher Gratuito"),
                        ],
                        default="MANUAL",
                        max_length=20,
                        verbose_name="Tipo de Vínculo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("APROVADO", "Aprovado"),
                            ("RECUSADO", "Recusado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="APROVADO",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_aprovacao",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data em que o vínculo foi aprovado",
                        null=True,
                        verbose_name="Data de Aprovação",
                    ),
                ),
                (
                    "data_cancelamento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Cancelamento"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True,
                        help_text="Informações adicionais sobre o vínculo",
                        verbose_name="Observações",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarque para desativar o vínculo sem deletar",
                        verbose_name="Vínculo Ativo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "espaco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculos_terapeutas",
                        to="espacos.espaco",
                        verbose_name="Espaço",
                    ),
                ),
                (
                    "terapeuta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculos_espacos",
                        to="terapeutas.terapeuta",
                        verbose_name="Terapeuta",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        blank=True,
                        help_text="Voucher usado para criar este vínculo (se aplicável)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vinculos",
                        to="core.voucher",
                        verbose_name="Voucher Utilizado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vínculo Terapeuta-Espaço",
                "verbose_name_plural": "Vínculos Terapeuta-Espaço",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["espaco", "terapeuta", "status"],
                        name="agendamento_espaco__337aa4_idx",
                    ),
                    models.Index(
                        fields=["status", "is_active"],
                        name="agendamento_status_10840a_idx",
                    ),
                ],
                "unique_together": {("espaco", "terapeuta")},
            },
        ),
    ]
