# Generated by Django 4.2.15 on 2026-01-03 18:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agendamentos", "0003_vinculoterapeutaespaco"),
    ]

    operations = [
        migrations.AddField(
            model_name="sala",
            name="prazo_cancelamento_sem_multa",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Tempo mínimo de antecedência para cancelar sem multa (padrão: 60 minutos)",
                verbose_name="Prazo para Cancelamento Sem Multa (minutos)",
            ),
        ),
        migrations.AddField(
            model_name="sala",
            name="valor_multa_cancelamento",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Multa cobrada se cancelar com menos de 1 hora de antecedência",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Valor da Multa por Cancelamento",
            ),
        ),
    ]
