# Generated by Django 4.2.15 on 2026-05-31 07:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("espacos", "0009_remove_espaco_disponibilidade_and_more"),
        ("agendamentos", "0004_add_regras_cancelamento_sala"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConviteExterno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Email do Convidado"
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="Token do Convite"
                    ),
                ),
                ("mensagem", models.TextField(blank=True, verbose_name="Mensagem")),
                (
                    "usado",
                    models.BooleanField(
                        default=False,
                        help_text="Token já foi utilizado no cadastro",
                        verbose_name="Usado",
                    ),
                ),
                ("expira_em", models.DateTimeField(verbose_name="Expira em")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "espaco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="convites_externos",
                        to="espacos.espaco",
                        verbose_name="Espaço",
                    ),
                ),
            ],
            options={
                "verbose_name": "Convite Externo",
                "verbose_name_plural": "Convites Externos",
                "ordering": ["-created_at"],
            },
        ),
    ]
